"""
NyayaSaathi — PDF Export
Converts complaint letters to PDF using fpdf2.
"""

import os
from datetime import datetime
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

OUTPUT_PATH = os.getenv("OUTPUT_PATH", "./output")


def export_to_pdf(
    letter_text: str,
    user_name: str = "Complainant",
    output_dir: str = OUTPUT_PATH,
) -> str:
    """
    Export a complaint letter string to a PDF file.

    Args:
        letter_text: The full text of the complaint letter
        user_name: Used in filename generation
        output_dir: Directory to save the PDF

    Returns:
        Absolute path to the generated PDF file
    """
    from fpdf import FPDF

    # Ensure output directory exists
    Path(output_dir).mkdir(parents=True, exist_ok=True)

    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_name = "".join(c if c.isalnum() else "_" for c in user_name)[:20]
    filename = f"complaint_{safe_name}_{timestamp}.pdf"
    filepath = os.path.join(output_dir, filename)

    # Create PDF
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Header
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(20, 60, 120)
    pdf.cell(0, 10, "NyayaSaathi — Legal Complaint Letter", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 6, "Generated by NyayaSaathi | Works 100% Offline | Your data never left your device", ln=True, align="C")
    pdf.ln(4)

    # Divider line
    pdf.set_draw_color(20, 60, 120)
    pdf.set_line_width(0.5)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(6)

    # Body — letter content
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(0, 0, 0)

    # Process letter line by line for proper formatting
    lines = letter_text.split("\n")
    for line in lines:
        line = line.rstrip()

        # Section headers (ALL CAPS lines or numbered headers)
        if (line.isupper() and len(line) > 3) or (
            len(line) > 2 and line[0].isdigit() and "." in line[:4] and line[2:4].isupper()
        ):
            pdf.set_font("Helvetica", "B", 11)
            pdf.multi_cell(0, 7, line)
            pdf.set_font("Helvetica", "", 11)
        elif line.startswith("Subject:") or line.startswith("To,") or line.startswith("Sir/Madam"):
            pdf.set_font("Helvetica", "B", 11)
            pdf.multi_cell(0, 7, line)
            pdf.set_font("Helvetica", "", 11)
        elif line == "":
            pdf.ln(3)
        else:
            pdf.multi_cell(0, 7, line)

    # Footer
    pdf.ln(6)
    pdf.set_draw_color(20, 60, 120)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(140, 140, 140)
    pdf.cell(
        0, 5,
        f"Generated on {datetime.now().strftime('%d %B %Y at %H:%M')} | "
        "Free legal aid: Contact your District Legal Services Authority (DLSA)",
        ln=True, align="C"
    )

    # Save PDF
    pdf.output(filepath)
    abs_path = str(Path(filepath).resolve())
    print(f"PDF saved: {abs_path}")
    return abs_path


if __name__ == "__main__":
    sample_letter = """New Delhi, April 12, 2026

To,
The Authority under Payment of Wages Act,
Office of the Labour Commissioner,
Patna, Bihar

Subject: Complaint for Non-Payment of Wages under Payment of Wages Act 1936

Sir/Madam,

1. FACTS OF THE CASE:
I, Ramesh Kumar, was employed as a Security Guard with ABC Security Services Pvt Ltd, 456 Industrial Area, Patna, from January 2026. My agreed monthly salary is Rs. 12,000.

My employer has failed to pay my salary for the past 3 months (January, February, March 2026), totaling Rs. 36,000 in unpaid wages.

2. LEGAL BASIS:
Under Section 5 of the Payment of Wages Act 1936, wages must be paid within 7 days of the end of the wage period. The failure to do so constitutes a violation of this Act.

3. PRAYER/RELIEF SOUGHT:
1. Direction to employer to pay Rs. 36,000 in arrears of wages immediately.
2. Compensation under Section 15(3) of the Act.
3. Recovery as arrears of land revenue if employer defaults.

I therefore pray that you may kindly take appropriate action in the matter.

Thanking you,

Yours faithfully,

Ramesh Kumar
123 MG Road, Patna, Bihar - 800001
Phone: 9876543210"""

    path = export_to_pdf(sample_letter, user_name="Ramesh Kumar")
    print(f"Test PDF created at: {path}")
